name: Deploy Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Configure Serverless AWS credentials
        run: serverless config credentials --provider aws --key=${{ secrets.AWS_ACCESS_KEY }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} -o

      - name: Build and Deploy Lambda
        run: |
          make deploy_prod
